export const GET_RECIPES = 'GET_RECIPES';
export const FILTER_BY_DIET='FILTER_BY_DIET';
export const FILTER_CREATED = 'FILTER_CREATED';
export const GET_BY_NAME = 'GET_RECIPE_BY_NAME';
export const GET_BY_ID = 'GET_RECIPE_BY_ID';
export const ORDER_BY_NAME ='ORDER_BY_NAME';
export const ORDER_BY_SCORE ='ORDER_BY_SCORE';
export const GET_DIETS = 'GET_DIETS';
export const POST_RECIPES = 'POST_RECIPES';